GET http://localhost:1234/movies

###

GET http://localhost:1234/movies/241bf55d-b649-4109-af7c-0e6890ded3fc

###

GET http://localhost:1234/movies?genre=Sci-Fi

###

POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "Hola",
  "year": 2025,
  "director": "Leonel Almanza Medina",
  "duration": 200,
  "poster": "https://img.jpg",
  "genre": [
    "Dream"
  ],
  "rate": 10
}

###

PATCH http://localhost:1234/movies/241bf55d-b649-4109-af7c-0e6890ded3fc
Content-Type: application/json

{
  "id": "Hola",
  "director": "Felipe Guzman Alvarado",
  "rate": 5.8
}